//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelMVC0806.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int id { get; set; }
        public int Departmanid { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public decimal Maaş { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public bool Cinsiyet { get; set; }
        public bool MedeniDurumu { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
